from typing import List, Dict, Any, Tuple
import json
import re
from functools import lru_cache
from app.models import Recipe

import unicodedata
import html


def _normalize(ingredient: str) -> str:
    normalized = unicodedata.normalize('NFD', ingredient.strip().lower())
    normalized = ''.join(c for c in normalized if unicodedata.category(c) != 'Mn')
    normalized = re.sub(r"[^a-z0-9\s]", "", normalized)
    return normalized.strip()


def _strip_accents(text: str) -> str:
    normalized = unicodedata.normalize('NFD', text)
    return ''.join(c for c in normalized if unicodedata.category(c) != 'Mn')


def _clean_ingredient_name(raw: str) -> str:
    cleaned = html.unescape(raw.strip())
    if not cleaned:
        return ""
    cleaned = cleaned.lower()
    prev = None
    while cleaned != prev:
        prev = cleaned
        cleaned = re.sub(r'^\(\d[\d\s/]*\.?\d*\s*[^)]*\)\s*', '', cleaned)
        cleaned = re.sub(r'^(?:\.?\d+[\d/\-]*\.?\d*\s*)?', '', cleaned)
    units = re.compile(
        r'\b(?:cups?|tbsp|tsp|tablespoons?|teaspoons?|ounces?|oz|lbs?|pounds?|grams?|kg|g|ml|l|cloves?|pinches?|dashes?|cans?|packages?|jars?|bottles?|slices?|pieces?|sprigs?|stalks?|leaves?|cloves?|whole|large|medium|small|big|to taste|as needed|finely|thinly|diced|chopped|minced|sliced|optional|divided|plus|more|extra)\s+',
        re.IGNORECASE
    )
    cleaned = units.sub('', cleaned)
    if ',' in cleaned:
        cleaned = cleaned.split(',')[0].strip()
    cleaned = re.sub(r'^[%"\']+\s*', '', cleaned)
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()
    if not cleaned or len(cleaned) < 2:
        cleaned = raw.strip().lower()
        cleaned = re.sub(r'\s+', ' ', cleaned).strip()
    translated = _TRANSLATIONS.get(cleaned)
    if translated:
        return translated
    return cleaned


_TRANSLATIONS = {
    "ahi": "atún ahi",
    "ahi tuna steaks": "filetes de atún ahi",
    "albacore tuna": "atún albacora",
    "albacore tuna in water": "atún albacora en agua",
    "ale": "cerveza ale",
    "alligator meat": "carne de caimán",
    "allspice": "pimienta de jamaica",
    "allspice berries": "bayas de pimienta de jamaica",
    "allspice berry": "baya de pimienta de jamaica",
    "almond butter": "mantequilla de almendra",
    "almond flavored liqueur": "licor de almendra",
    "almond paste": "pasta de almendra",
    "aluminum foil": "papel aluminio",
    "amaretti cookies": "galletas amaretti",
    "amaretto liqueur": "licor amaretto",
    "amaretto sweetened condensed milk": "leche condensada amaretto",
    "amarula cream liqueur": "licor de crema amarula",
    "american cheese": "queso americano",
    "anchov": "anchoa",
    "anchovy": "anchoa",
    "anchovy fillet": "filete de anchoa",
    "anchovy fillets": "filetes de anchoa",
    "anchovy paste": "pasta de anchoa",
    "anchovies": "anchoas",
    "angel hair pasta": "pasta cabello de ángel",
    "angel flake coconut": "coco en copos",
    "angelica": "angélica",
    "angelica leaf": "hoja de angélica",
    "angelica leaves": "hojas de angélica",
    "anise": "anís",
    "anise seed": "semilla de anís",
    "anise seeds": "semillas de anís",
    "anjou pear": "pera anjou",
    "anjou pears": "peras anjou",
    "annatto oil": "aceite de achiote",
    "annatto seed": "semilla de achiote",
    "annatto seeds": "semillas de achiote",
    "apple": "manzana",
    "apple butter": "mantequilla de manzana",
    "apple cider": "sidra de manzana",
    "apple cider vinegar": "vinagre de sidra de manzana",
    "apple juice": "jugo de manzana",
    "apple pie spice": "especia para pie de manzana",
    "apples": "manzanas",
    "applesauce": "compota de manzana",
    "apricot": "albaricoque",
    "apricot brandy": "brandy de albaricoque",
    "apricot chutney": "chutney de albaricoque",
    "apricot jam": "mermelada de albaricoque",
    "apricot marmalade": "mermelada de albaricoque",
    "apricots": "albaricoques",
    "arborio rice": "arroz arborio",
    "arrowroot": "arrurruz",
    "artichoke": "alcachofa",
    "artichoke bottom": "fondo de alcachofa",
    "artichoke bottoms": "fondos de alcachofa",
    "artichoke heart": "corazón de alcachofa",
    "artichoke hearts": "corazones de alcachofa",
    "artichokes": "alcachofas",
    "arugula": "rúcula",
    "asparagus": "espárrago",
    "asparagus spear": "punta de espárrago",
    "asparagus spears": "puntas de espárrago",
    "asparagus tips": "puntas de espárrago",
    "avocado": "palta",
    "avocado dip": "dip de palta",
    "avocado oil": "aceite de palta",
    "avocados": "paltas",
    "bacon": "tocino",
    "bacon bits": "trocitos de tocino",
    "bacon drippings": "grasa de tocino",
    "bacon fat": "grasa de tocino",
    "bacon grease": "grasa de tocino",
    "baking apple": "manzana para hornear",
    "baking chocolate": "chocolate para hornear",
    "baking mix": "mezcla para hornear",
    "baking powder": "polvo de hornear",
    "baking potato": "papa para hornear",
    "baking soda": "bicarbonato de sodio",
    "balsamic vinegar": "vinagre balsámico",
    "bamboo shoots": "brotes de bambú",
    "banana": "plátano",
    "banana instant pudding": "pudín instantáneo de plátano",
    "banana pepper": "ají banano",
    "banana peppers": "ajíes banano",
    "bananas": "plátanos",
    "barbecued pork": "cerdo barbacoa",
    "basil": "albahaca",
    "basil leaves": "hojas de albahaca",
    "basil pesto": "pesto de albahaca",
    "basil sprig": "rama de albahaca",
    "basil sprigs": "ramas de albahaca",
    "bay leaf": "hoja de laurel",
    "bay leaves": "hojas de laurel",
    "bay scallop": "vieira",
    "bay shrimp": "camarón bay",
    "bean paste": "pasta de frijol",
    "bean sprouts": "brotes de frijol",
    "bean thread noodles": "fideos de frijol",
    "bean thread vermicelli": "vermicelli de frijol",
    "bean threads": "hilos de frijol",
    "beans": "frijoles",
    "beef": "carne de res",
    "beef barbecue": "carne de res barbacoa",
    "beef bouillon cube": "cubo de caldo de res",
    "beef bouillon cubes": "cubos de caldo de res",
    "beef bouillon granules": "gránulos de caldo de res",
    "beef bouillon powder": "polvo de caldo de res",
    "beef brisket": "pecho de res",
    "beef broth": "caldo de res",
    "beef chuck": "paleta de res",
    "beef liver": "hígado de res",
    "beef rib": "costilla de res",
    "beef round": "redondo de res",
    "beef shank": "jarrete de res",
    "beef short rib": "costilla corta de res",
    "beef sirloin": "solomo de res",
    "beef stew": "estofado de res",
    "beef stock": "caldo de res",
    "beef stroganoff": "stroganoff de res",
    "beef tenderloin": "solomo de res tierno",
    "beet": "remolacha",
    "beetroot": "remolacha",
    "beets": "remolachas",
    "bell pepper": "pimiento",
    "bell peppers": "pimientos",
    "berries": "bayas",
    "berry": "baya",
    "bibb lettuce": "lechuga bibb",
    "bibb or boston lettuce": "lechuga bibb o boston",
    "black beans": "frijoles negros",
    "black cumin": "comino negro",
    "black-eyed peas": "frejoles de ojo negro",
    "black olive": "aceituna negra",
    "black olives": "aceitunas negras",
    "black pepper": "pimienta negra",
    "black peppercorn": "grano de pimienta negra",
    "black peppercorns": "granos de pimienta negra",
    "black sesame seeds": "semillas de sésamo negro",
    "black-eyed pea": "frejol de ojo negro",
    "blanched almonds": "almendras blanqueadas",
    "blood orange": "naranja sanguina",
    "blue cheese": "queso azul",
    "blue potato": "papa azul",
    "boiling potato": "papa para hervir",
    "boiling potatoes": "papas para hervir",
    "bok choy": "col china",
    "boston lettuce": "lechuga boston",
    "boston lettuce leaves": "hojas de lechuga boston",
    "bouillon cube": "cubo de caldo",
    "bouillon cubes": "cubos de caldo",
    "bouillon powder": "polvo de caldo",
    "bourbon": "bourbon",
    "bow-tie pasta": "pasta mariposa",
    "boysenberry": "boysenberry",
    "bran": "salvado",
    "brandy": "brandy",
    "bread": "pan",
    "bread flour": "harina de pan",
    "bread machine yeast": "levadura para pan",
    "bread crumbs": "pan rallado",
    "bread crumb": "miga de pan",
    "breadcrumb": "pan rallado",
    "breadcrumbs": "pan rallado",
    "brie": "queso brie",
    "broad beans": "habas anchas",
    "broccoli": "brócoli",
    "broccoli coleslaw mix": "mezcla de col de brócoli",
    "broccoli floret": "flor de brócoli",
    "broccoli florets": "flores de brócoli",
    "broccoli rabe": "brócoli rabe",
    "broccoli slaw mix": "mezcla para ensalada de brócoli",
    "broccoli slaw": "ensalada de brócoli",
    "broccoli sprouts": "brotes de brócoli",
    "broccoli stem": "tallo de brócoli",
    "broccoli stems": "tallos de brócoli",
    "brown lentils": "lentejas marrones",
    "brown mustard": "mostaza marrón",
    "brown mustard seeds": "semillas de mostaza marrón",
    "brown sugar": "azúcar moreno",
    "brown sugar substitute": "sustituto de azúcar moreno",
    "browning": "caramelo para dorar",
    "brussels sprout": "col de bruselas",
    "brussels sprouts": "coles de bruselas",
    "buffalo mozzarella": "mozzarella de búfala",
    "bulgur": "bulgur",
    "buns": "panes",
    "butter": "mantequilla",
    "butter flavor shortening": "acortamiento sabor mantequilla",
    "butter lettuce": "lechuga manteca",
    "butter lettuce leaf": "hoja de lechuga manteca",
    "butter lettuce leaves": "hojas de lechuga manteca",
    "buttermilk": "suero de leche",
    "buttermilk baking mix": "mezcla para hornear con suero",
    "buttermilk biscuit mix": "mezcla para galletas con suero",
    "butternut squash": "zapallo butternut",
    "cabbage": "repollo",
    "cabbage coleslaw blend": "mezcla de ensalada de repollo",
    "cabbage leaves": "hojas de repollo",
    "cacciatore": "a la cacciatora",
    "canned black beans": "frijoles negros enlatados",
    "canned chick-peas": "garbanzos enlatados",
    "canned chopped tomatoes": "tomates picados enlatados",
    "canned corn": "choclo enlatado",
    "canned diced tomatoes": "tomates cubeados enlatados",
    "canned kidney beans": "frijoles rojos enlatados",
    "canned milk": "leche enlatada",
    "canned navy beans": "frijoles navy enlatados",
    "canned pinto beans": "frijoles pinto enlatados",
    "canned pimiento": "pimentón enlatado",
    "canned salmon": "salmón enlatado",
    "canned sardines": "sardinas enlatadas",
    "canned sweet potatoes": "camotes enlatados",
    "canned tomato": "tomate enlatado",
    "canned tomato sauce": "salsa de tomate enlatada",
    "canned tomatoes": "tomates enlatados",
    "canned tuna": "atún enlatado",
    "canned unsweetened coconut milk": "leche de coco sin azúcar enlatada",
    "canned white beans": "frijoles blancos enlatados",
    "canned white tuna": "atún blanco enlatado",
    "capers": "alcaparras",
    "capers capers": "alcaparras",
    "caramel": "caramelo",
    "caramel ice cream": "helado de caramelo",
    "caramel sauce": "salsa de caramelo",
    "caramel swirl": "remolino de caramelo",
    "caramel-swirl ice cream": "helado con remolino de caramelo",
    "caraway seed": "semilla de alcaravea",
    "caraway seeds": "semillas de alcaravea",
    "cardamom": "cardamomo",
    "cardamom pod": "vaina de cardamomo",
    "cardamom pods": "vainas de cardamomo",
    "carnation evaporated milk": "leche evaporada carnation",
    "carrot": "zanahoria",
    "carrots": "zanahorias",
    "cashew": "castaña de cajú",
    "cashew nuts": "nueces de cajú",
    "cashews": "nueces de cajú",
    "cassava": "yuca",
    "cassava flour": "harina de yuca",
    "cassava meal": "harina de yuca",
    "catfish": "bagre",
    "cauliflower": "coliflor",
    "cauliflower florets": "flores de coliflor",
    "cayenne": "pimienta de cayena",
    "cayenne pepper": "pimienta de cayena",
    "celery": "apio",
    "celery heart": "corazón de apio",
    "celery hearts": "corazones de apio",
    "celery rib": "rama de apio",
    "celery ribs": "ramas de apio",
    "celery root": "raíz de apio",
    "celery salt": "sal de apio",
    "celery seed": "semilla de apio",
    "celery seeds": "semillas de apio",
    "celery stalk": "tallo de apio",
    "celery stalks": "tallos de apio",
    "celery stick": "bastón de apio",
    "celery sticks": "bastones de apio",
    "cereal": "cereal",
    "champagne vinegar": "vinagre de champaña",
    "cheddar cheese": "queso cheddar",
    "cheese": "queso",
    "cheesecloth": "gasa para queso",
    "cherry": "cereza",
    "cherry jam": "mermelada de cereza",
    "cherry juice": "jugo de cereza",
    "cherry tomato": "tomate cherry",
    "cherry tomatoes": "tomates cherry",
    "cherries": "cerezas",
    "chestnut": "castaña",
    "chestnuts": "castañas",
    "chia seeds": "semillas de chía",
    "chicken": "pollo",
    "chicken bouillon": "caldo de pollo",
    "chicken bouillon cube": "cubo de caldo de pollo",
    "chicken bouillon granules": "gránulos de caldo de pollo",
    "chicken broth": "caldo de pollo",
    "chicken breast": "pechuga de pollo",
    "chicken breasts": "pechugas de pollo",
    "chicken drumstick": "muslo de pollo",
    "chicken drumsticks": "muslos de pollo",
    "chicken leg": "pierna de pollo",
    "chicken legs": "piernas de pollo",
    "chicken liver": "hígado de pollo",
    "chicken livers": "hígados de pollo",
    "chicken pieces": "trozos de pollo",
    "chicken stock": "caldo de pollo",
    "chicken thigh": "muslo de pollo",
    "chicken thighs": "muslos de pollo",
    "chicken wing": "ala de pollo",
    "chicken wings": "alas de pollo",
    "chickpea": "garbanzo",
    "chickpeas": "garbanzos",
    "chicory": "achicoria",
    "chili": "ají",
    "chili bean": "frijol picante",
    "chili beans": "frijoles picantes",
    "chili flake": "hojuela de ají",
    "chili flakes": "hojuelas de ají",
    "chili paste": "pasta de ají",
    "chili pepper": "ají picante",
    "chili peppers": "ajíes picantes",
    "chili powder": "polvo de ají",
    "chili sauce": "salsa de ají",
    "chipotle": "chipotle",
    "chipotle chile": "chile chipotle",
    "chipotle chilies": "chiles chipotle",
    "chipotle pepper": "ají chipotle",
    "chipotle peppers": "ajíes chipotle",
    "chipotle powder": "polvo de chipotle",
    "chipotle salsa": "salsa de chipotle",
    "chives": "cebollín",
    "chocolate": "chocolate",
    "chocolate bar": "barra de chocolate",
    "chocolate chips": "chips de chocolate",
    "chocolate chunks": "trozos de chocolate",
    "chopped parsley": "perejil picado",
    "chorizo": "chorizo",
    "cider vinegar": "vinagre de sidra",
    "cilantro": "cilantro",
    "cilantro leaves": "hojas de cilantro",
    "cinnamon": "canela",
    "cinnamon stick": "rama de canela",
    "cinnamon sticks": "ramas de canela",
    "clam": "almeja",
    "clam juice": "jugo de almeja",
    "clams": "almejas",
    "clam sauce": "salsa de almeja",
    "clove": "clavo de olor",
    "clove garlic": "diente de ajo",
    "clove garlic minced": "diente de ajo picado",
    "cloves": "clavos de olor",
    "cloves garlic": "dientes de ajo",
    "coarse salt": "sal gruesa",
    "cocoa": "cacao",
    "cocoa powder": "cacao en polvo",
    "coconut": "coco",
    "coconut cream": "crema de coco",
    "coconut extract": "extracto de coco",
    "coconut flakes": "copos de coco",
    "coconut milk": "leche de coco",
    "coconut oil": "aceite de coco",
    "coconut sugar": "azúcar de coco",
    "coconut water": "agua de coco",
    "cod": "bacalao",
    "coffee": "café",
    "coffee liqueur": "licor de café",
    "cognac": "coñac",
    "cola": "cola",
    "cold water": "agua fría",
    "condensed milk": "leche condensada",
    "confectioners sugar": "azúcar impalpable",
    "coriander": "cilantro",
    "coriander seeds": "semillas de cilantro",
    "corn": "choclo",
    "corn bread": "pan de choclo",
    "corn flour": "harina de choclo",
    "corn meal": "harina de maíz",
    "corn oil": "aceite de maíz",
    "corn starch": "maicena",
    "corn syrup": "jarabe de maíz",
    "corn tortilla": "tortilla de choclo",
    "corn tortillas": "tortillas de choclo",
    "cornstarch": "maicena",
    "cottage cheese": "queso cottage",
    "couscous": "cuscús",
    "cow peas": "frijoles de vaca",
    "crab": "cangrejo",
    "crab meat": "carne de cangrejo",
    "crabmeat": "carne de cangrejo",
    "cracked black pepper": "pimienta negra molida gruesa",
    "cracked pepper": "pimienta molida gruesa",
    "cranberry": "arándano rojo",
    "cranberry juice": "jugo de arándano rojo",
    "cranberry sauce": "salsa de arándano rojo",
    "cranberries": "arándanos rojos",
    "cream": "crema",
    "cream cheese": "queso crema",
    "cream of coconut": "crema de coco",
    "cream of mushroom soup": "crema de champiñones",
    "cream of tartar": "cremor tártaro",
    "creamed corn": "choclo cremoso",
    "crema": "crema",
    "crema mexicana": "crema mexicana",
    "creme fraiche": "crema fresca",
    "crescent roll": "rolico de media luna",
    "crescent rolls": "rolicos de media luna",
    "croissant": "cruasán",
    "croissants": "cruasanes",
    "croutons": "crutones",
    "cucumber": "pepino",
    "cucumbers": "pepinos",
    "cumin": "comino",
    "cumin seed": "semilla de comino",
    "cumin seeds": "semillas de comino",
    "cupcake": "magdalenas",
    "cupcakes": "magdalenas",
    "currant": "grosella",
    "currants": "grosellas",
    "curry": "curry",
    "curry leaf": "hoja de curry",
    "curry leaves": "hojas de curry",
    "curry paste": "pasta de curry",
    "curry powder": "polvo de curry",
    "custard": "flan",
    "dairy": "lácteos",
    "dark brown sugar": "azúcar moreno oscuro",
    "dark chocolate": "chocolate amargo",
    "dark chocolate chips": "chips de chocolate amargo",
    "dates": "dátiles",
    "demerara sugar": "azúcar demerara",
    "desiccated coconut": "coco rallado deshidratado",
    "dijon mustard": "mostaza dijon",
    "dill": "eneldo",
    "dill weed": "verdura de eneldo",
    "double cream": "doble crema",
    "dried apricots": "albaricoques secos",
    "dried basil": "albahaca seca",
    "dried beans": "frijoles secos",
    "dried cherries": "cerezas secas",
    "dried chickpeas": "garbanzos secos",
    "dried chives": "cebollín seco",
    "dried cranberries": "arándanos rojos secos",
    "dried fruit": "fruta seca",
    "dried herbs": "hierbas secas",
    "dried kidney beans": "frijoles rojos secos",
    "dried lavender": "lavanda seca",
    "dried lentils": "lentejas secas",
    "dried mango": "mango seco",
    "dried marjoram": "mejorana seca",
    "dried mint": "menta seca",
    "dried mushrooms": "champiñones secos",
    "dried oregano": "orégano seco",
    "dried parsley": "perejil seco",
    "dried peas": "arvejas secas",
    "dried porcini mushrooms": "hongos porcini secos",
    "dried raisins": "pasas",
    "dried red lentils": "lentejas rojas secas",
    "dried rosemary": "romero seco",
    "dried sage": "salvia seca",
    "dried thyme": "tomillo seco",
    "dried tomatoes": "tomates secos",
    "dry white wine": "vino blanco seco",
    "dry yeast": "levadura seca",
    "dulce de leche": "dulce de leche",
    "egg": "huevo",
    "egg beaters": "sustituto de huevo",
    "egg beaters egg substitute": "sustituto de huevo egg beaters",
    "egg substitute": "sustituto de huevo",
    "egg white": "clara de huevo",
    "egg whites": "claras de huevo",
    "egg yolk": "yema de huevo",
    "egg yolks": "yemas de huevo",
    "eggplant": "berenjena",
    "eggplants": "berenjenas",
    "eggs": "huevos",
    "eggshells": "cáscaras de huevo",
    "endive": "endibia",
    "english cucumber": "pepino inglés",
    "english muffin": "pan inglés",
    "english muffins": "panes ingleses",
    "espresso": "exprés",
    "extra-virgin olive oil": "aceite de oliva virgen extra",
    "fartons": "fartons",
    "fennel": "hinojo",
    "fennel bulb": "bulbo de hinojo",
    "fennel frond": "ramillete de hinojo",
    "fennel fronds": "ramilletes de hinojo",
    "fennel seed": "semilla de hinojo",
    "fennel seeds": "semillas de hinojo",
    "feta": "queso feta",
    "feta cheese": "queso feta",
    "fiber one": "fibra uno",
    "fideo": "fideo",
    "fideos": "fideos",
    "fig": "higo",
    "figs": "higos",
    "filet mignon": "filet mignon",
    "filete de res": "filete de res",
    "filete of beef": "filete de res",
    "filetes de res": "filetes de res",
    "fish": "pescado",
    "fish fillet": "filete de pescado",
    "fish fillets": "filetes de pescado",
    "fish sauce": "salsa de pescado",
    "fish stock": "caldo de pescado",
    "flank steak": "falda de res",
    "flour": "harina",
    "flour tortilla": "tortilla de harina",
    "flour tortillas": "tortillas de harina",
    "focaccia": "focaccia",
    "foccacia": "focaccia",
    "fontina cheese": "queso fontina",
    "french bread": "pan francés",
    "french fries": "papas fritas",
    "french loaf": "baguette",
    "french lentil": "lenteja francesa",
    "fresh basil": "albahaca fresca",
    "fresh bay leaves": "hojas de laurel frescas",
    "fresh beans": "frijoles frescos",
    "fresh blueberries": "arándanos frescos",
    "fresh breadcrumbs": "pan rallado fresco",
    "fresh chives": "cebollín fresco",
    "fresh cilantro": "cilantro fresco",
    "fresh corn": "choclo fresco",
    "fresh corn kernels": "granos de choclo fresco",
    "fresh cranberries": "arándanos rojos frescos",
    "fresh dill": "eneldo fresco",
    "fresh flat leaf parsley": "perejil de hoja plana fresco",
    "fresh fruit": "fruta fresca",
    "fresh ginger": "jengibre fresco",
    "fresh lemon juice": "jugo de limón fresco",
    "fresh lattice": "queso fresco",
    "fresh lime juice": "jugo de lima fresco",
    "fresh marjoram": "mejorana fresca",
    "fresh mint": "menta fresca",
    "fresh mozzarella": "mozzarella fresca",
    "fresh mozzarella ball": "bola de mozzarella fresca",
    "fresh mozzarella balls": "bolas de mozzarella fresca",
    "fresh mushrooms": "champiñones frescos",
    "fresh oregano": "orégano fresco",
    "fresh parsley": "perejil fresco",
    "fresh parsley leaves": "hojas de perejil fresco",
    "fresh raspberries": "frambuesas frescas",
    "fresh ricotta": "ricotta fresca",
    "fresh rosemary": "romero fresco",
    "fresh sage": "salvia fresca",
    "fresh spinach": "espinaca fresca",
    "fresh thyme": "tomillo fresco",
    "fresh tomato": "tomate fresco",
    "fresh tomatoes": "tomates frescos",
    "fresh yeast": "levadura fresca",
    "fried onion": "cebolla frita",
    "fried onions": "cebollas fritas",
    "frisee": "escarola",
    "frozen blueberries": "arándanos congelados",
    "frozen bread dough": "masa de pan congelada",
    "frozen broccoli": "brócoli congelado",
    "frozen brownie": "brownie congelado",
    "frozen peas": "arvejas congeladas",
    "frozen spinach": "espinaca congelada",
    "frozen strawberries": "frutillas congeladas",
    "frozen tater tots": "tater tots congelados",
    "frozen vegetables": "verduras congeladas",
    "fudge": "dulce de chocolate",
    "fuji apple": "manzana fuji",
    "galangal": "galanga",
    "garam masala": "garam masala",
    "garbanzo bean": "garbanzo",
    "garbanzo beans": "garbanzos",
    "garlic": "ajo",
    "garlic clove": "diente de ajo",
    "garlic cloves": "dientes de ajo",
    "garlic powder": "ajo en polvo",
    "garlic salt": "sal de ajo",
    "garlic sauce": "salsa de ajo",
    "gelatin": "gelatina",
    "gelatin powder": "polvo de gelatina",
    "gelato": "helado italiano",
    "ghee": "ghee",
    "ginger": "jengibre",
    "ginger ale": "ginger ale",
    "ginger beer": "cerveza de jengibre",
    "ginger paste": "pasta de jengibre",
    "ginger root": "raíz de jengibre",
    "gingersnap cookie": "galleta de jengibre",
    "gingersnap cookies": "galletas de jengibre",
    "glaze": "glaseado",
    "gluten": "gluten",
    "gluten free": "sin gluten",
    "gnocchi": "ñoquis",
    "goat cheese": "queso de cabra",
    "goat meat": "carne de cabra",
    "golden raisins": "pasas rubias",
    "gouda": "queso gouda",
    "gouda cheese": "queso gouda",
    "granola": "granola",
    "granulated garlic": "ajo granulado",
    "granulated onion": "cebolla granulada",
    "grape": "uva",
    "grape tomato": "tomate uva",
    "grape tomatoes": "tomates uva",
    "grapefruit": "pomelo",
    "grapefruit juice": "jugo de pomelo",
    "grapes": "uvas",
    "grated cheese": "queso rallado",
    "grated parmesan": "queso parmesano rallado",
    "green beans": "judías verdes",
    "green bell pepper": "pimiento verde",
    "green bell peppers": "pimientos verdes",
    "green cabbage": "repollo verde",
    "green cardamom": "cardamomo verde",
    "green cardamom pods": "vainas de cardamomo verde",
    "green chili": "ají verde",
    "green chilies": "ajíes verdes",
    "green chili pepper": "ají verde picante",
    "green chili peppers": "ajíes verdes picantes",
    "green chile": "chile verde",
    "green chiles": "chiles verdes",
    "green lentil": "lenteja verde",
    "green lentils": "lentejas verdes",
    "green leaf lettuce": "lechuga hoja verde",
    "green olives": "aceitunas verdes",
    "green onion": "cebolla de verdeo",
    "green onions": "cebollas de verdeo",
    "green pea": "arveja",
    "green peas": "arvejas",
    "green pepper": "pimiento verde",
    "green peppers": "pimientos verdes",
    "green plantain": "plátano verde",
    "green plantains": "plátanos verdes",
    "green soybeans": "porotos verdes",
    "greens": "verduras de hoja verde",
    "grill": "parrilla",
    "ground allspice": "pimienta de jamaica molida",
    "ground beef": "carne molida",
    "ground cardamom": "cardamomo molido",
    "ground cayenne pepper": "pimienta de cayena molida",
    "ground chicken": "carne de pollo molida",
    "ground chile": "ají molido",
    "ground chocolate": "chocolate molido",
    "ground cinnamon": "canela molida",
    "ground cloves": "clavos de olor molidos",
    "ground coriander": "cilantro molido",
    "ground cumin": "comino molido",
    "ground flaxseed": "semilla de lino molida",
    "ground ginger": "jengibre molido",
    "ground lamb": "carne de cordero molida",
    "ground mace": "maza molida",
    "ground meat": "carne molida",
    "ground mustard": "mostaza molida",
    "ground nutmeg": "nuez moscada molida",
    "ground oregano": "orégano molido",
    "ground paprika": "pimentón molido",
    "ground pork": "carne de cerdo molida",
    "ground red pepper": "pimienta roja molida",
    "ground rosemary": "romero molido",
    "ground sage": "salvia molida",
    "ground star anise": "anís estrellado molido",
    "ground thyme": "tomillo molido",
    "ground turkey": "carne de pavo molida",
    "ground veal": "carne de ternera molida",
    "gruyere": "queso gruyere",
    "gruyere cheese": "queso gruyere",
    "guava": "guayaba",
    "gumbo": "gumbo",
    "habanero": "ají habanero",
    "habanero pepper": "ají habanero",
    "habanero peppers": "ajíes habanero",
    "half and half": "mitad crema mitad leche",
    "ham": "jamón",
    "ham bone": "hueso de jamón",
    "ham hock": "pata de jamón",
    "hamburger": "hamburguesa",
    "hamburger buns": "panes de hamburguesa",
    "hard-boiled egg": "huevo duro",
    "hard-boiled eggs": "huevos duros",
    "hash browns": "papas hash brown",
    "hazelnut": "avellana",
    "hazelnuts": "avellanas",
    "heavy cream": "crema de leche espesa",
    "herbs": "hierbas",
    "hibiscus": "hibisco",
    "hibiscus flowers": "flores de hibisco",
    "honey": "miel",
    "honey mustard": "mostaza con miel",
    "horseradish": "rábano picante",
    "hot dog": "pancho",
    "hot dog bun": "pan de pancho",
    "hot dog buns": "panes de pancho",
    "hot dogs": "panchos",
    "hot pepper": "ají picante",
    "hot pepper sauce": "salsa de ají picante",
    "hot sauce": "salsa picante",
    "ice": "hielo",
    "iceberg lettuce": "lechuga iceberg",
    "icing": "glaseado",
    "icing sugar": "azúcar impalpable",
    "idaho potato": "papa idaho",
    "instant yeast": "levadura instantánea",
    "irish cream": "crema irlandesa",
    "italian bread": "pan italiano",
    "italian dressing": "aderezo italiano",
    "italian herbs": "hierbas italianas",
    "italian sausage": "salchicha italiana",
    "jack cheese": "queso jack",
    "jalapeno": "jalapeño",
    "jalapeno pepper": "jalapeño",
    "jalapeno peppers": "jalapeños",
    "jam": "mermelada",
    "jelly": "jalea",
    "jerusalem artichoke": "tupinambo",
    "jicama": "jícama",
    "jimmies": "virutas de chocolate",
    "juice": "jugo",
    "jumbo shrimp": "camarones jumbo",
    "kale": "col rizada",
    "ketchup": "kétchup",
    "kielbasa": "kielbasa",
    "kidney beans": "frijoles rojos",
    "kirsch": "kirsch",
    "kiwi": "kiwi",
    "kiwifruit": "kiwi",
    "kosher salt": "sal kosher",
    "lamb": "cordero",
    "lamb chops": "costillas de cordero",
    "lamb shank": "jarrete de cordero",
    "lamb shoulder": "paleta de cordero",
    "lard": "manteca",
    "lasagna": "lasaña",
    "lasagna noodles": "fideos para lasaña",
    "lasagne": "lasaña",
    "lb": "libra",
    "lbs": "libras",
    "lean ground beef": "carne molida magra",
    "lean ground pork": "carne de cerdo molida magra",
    "leek": "puerro",
    "leeks": "puerros",
    "leg of lamb": "pernil de cordero",
    "lemon": "limón",
    "lemon extract": "extracto de limón",
    "lemon juice": "jugo de limón",
    "lemon peel": "cáscara de limón",
    "lemon pepper": "pimienta de limón",
    "lemon slice": "rodaja de limón",
    "lemon slices": "rodajas de limón",
    "lemon wedge": "gajo de limón",
    "lemon wedges": "gajos de limón",
    "lemon zest": "ralladura de limón",
    "lemons": "limones",
    "lentil": "lenteja",
    "lentils": "lentejas",
    "lettuce": "lechuga",
    "lettuce leaf": "hoja de lechuga",
    "lettuce leaves": "hojas de lechuga",
    "light corn syrup": "jarabe de maíz claro",
    "light cream": "crema ligera",
    "light mayonnaise": "mayonesa light",
    "light olive oil": "aceite de oliva light",
    "light soy sauce": "salsa de soja light",
    "lime": "lima",
    "lime juice": "jugo de lima",
    "lime peel": "cáscara de lima",
    "lime zest": "ralladura de lima",
    "limes": "limas",
    "linguine": "linguini",
    "liquid smoke": "humo líquido",
    "lobster": "langosta",
    "lobster meat": "carne de langosta",
    "long-grain rice": "arroz de grano largo",
    "low": "bajo",
    "low-carb tortilla": "tortilla baja en carbohidratos",
    "low-fat milk": "leche descremada",
    "low-sodium soy sauce": "salsa de soja bajo en sodio",
    "lumpia": "lumpia",
    "lupini beans": "altramuces",
    "macadamia": "macadamia",
    "macadamia nuts": "nueces de macadamia",
    "macaroni": "macarrones",
    "macaroni and cheese": "macarrones con queso",
    "mace": "maza",
    "mandarin orange": "mandarina",
    "mandarin oranges": "mandarinas",
    "mango": "mango",
    "mango chutney": "chutney de mango",
    "maple syrup": "jarabe de arce",
    "maraschino cherry": "cereza marrasquino",
    "maraschino cherries": "cerezas marrasquino",
    "margarine": "margarina",
    "marjoram": "mejorana",
    "marsala wine": "vino marsala",
    "marshmallow": "malvavisco",
    "marshmallows": "malvaviscos",
    "marzipan": "mazapán",
    "masa": "masa",
    "masa dough": "masa de maíz",
    "mascarpone": "queso mascarpone",
    "mascarpone cheese": "queso mascarpone",
    "matzo": "matzá",
    "matzo meal": "harina de matzá",
    "mayonnaise": "mayonesa",
    "meat": "carne",
    "meatballs": "albóndigas",
    "meatloaf": "pastel de carne",
    "medium apple": "manzana mediana",
    "medium onion": "cebolla mediana",
    "medium shrimp": "camarón mediano",
    "medium tomato": "tomate mediano",
    "melon": "melón",
    "meringue": "merengue",
    "mesclun": "mezcla de lechugas",
    "milk": "leche",
    "milk chocolate": "chocolate con leche",
    "minced garlic": "ajo picado",
    "minced ginger": "jengibre picado",
    "minced meat": "carne molida",
    "mint": "menta",
    "mint extract": "extracto de menta",
    "mint leaves": "hojas de menta",
    "molasses": "melaza",
    "monterey jack cheese": "queso monterey jack",
    "mozzarella": "mozzarella",
    "mozzarella cheese": "queso mozzarella",
    "mung beans": "frijoles mungo",
    "mushroom": "champiñón",
    "mushrooms": "champiñones",
    "mussels": "mejillones",
    "mustard": "mostaza",
    "mustard greens": "mostaza",
    "mustard seed": "semilla de mostaza",
    "mustard seeds": "semillas de mostaza",
    "mutton": "carne de cordero",
    "napa cabbage": "col china",
    "navy beans": "frijoles navy",
    "nectarine": "nectarina",
    "nectarines": "nectarinas",
    "nonfat milk": "leche descremada",
    "nonfat yogurt": "yogur descremado",
    "noodles": "fideos",
    "nutmeg": "nuez moscada",
    "nutritional yeast": "levadura nutricional",
    "oat": "avena",
    "oatmeal": "avena",
    "oats": "avena",
    "oil": "aceite",
    "oil-cured black olives": "aceitunas negras curadas en aceite",
    "oiled": "aceitado",
    "okra": "okra",
    "olive": "aceituna",
    "olive oil": "aceite de oliva",
    "olive oil cooking spray": "aceite de oliva en spray",
    "olives": "aceitunas",
    "onion": "cebolla",
    "onion powder": "cebolla en polvo",
    "onions": "cebollas",
    "orange": "naranja",
    "orange juice": "jugo de naranja",
    "orange liqueur": "licor de naranja",
    "orange marmalade": "mermelada de naranja",
    "orange peel": "cáscara de naranja",
    "orange zest": "ralladura de naranja",
    "oranges": "naranjas",
    "oregano": "orégano",
    "oregano leaves": "hojas de orégano",
    "oyster": "ostra",
    "oyster sauce": "salsa de ostras",
    "oysters": "ostras",
    "palm oil": "aceite de palma",
    "palm sugar": "azúcar de palma",
    "pancake": "panqueque",
    "pancakes": "panqueques",
    "pancetta": "panceta",
    "panko": "panko",
    "panko breadcrumbs": "pan rallado panko",
    "panko bread crumbs": "pan rallado panko",
    "papaya": "papaya",
    "paprika": "pimentón",
    "parmesan": "queso parmesano",
    "parmesan cheese": "queso parmesano",
    "parsley": "perejil",
    "parsley flakes": "copos de perejil",
    "parsley leaves": "hojas de perejil",
    "parsnip": "chirivía",
    "parsnips": "chirivías",
    "part-skim mozzarella cheese": "queso mozzarella semidescremado",
    "pasta": "pasta",
    "pasta sauce": "salsa para pasta",
    "pastry": "pastelería",
    "pastry flour": "harina de pastelería",
    "peach": "durazno",
    "peaches": "duraznos",
    "peanut": "maní",
    "peanut butter": "mantequilla de maní",
    "peanut oil": "aceite de maní",
    "peanuts": "maníes",
    "pear": "pera",
    "pearl barley": "cebada perlada",
    "pearl onions": "cebollitas perla",
    "pears": "peras",
    "peas": "arvejas",
    "pecan": "nuez pecan",
    "pecans": "nueces pecan",
    "peel": "cáscara",
    "penne": "penne",
    "penne pasta": "pasta penne",
    "pepper": "pimienta",
    "pepper jack cheese": "queso pepper jack",
    "peppercorn": "grano de pimienta",
    "peppercorns": "granos de pimienta",
    "pepperoni": "pepperoni",
    "peppers": "pimientos",
    "pesto": "pesto",
    "pickle": "pickle",
    "pickles": "pickles",
    "pickling salt": "sal para pickles",
    "pico de gallo": "pico de gallo",
    "pie crust": "tarta para pie",
    "pie shell": "corteza de pie",
    "pigeon peas": "gandules",
    "pine nut": "piñón",
    "pine nuts": "piñones",
    "pineapple": "piña",
    "pineapple chunks": "trozos de piña",
    "pineapple juice": "jugo de piña",
    "pineapple rings": "aros de piña",
    "pineapple tidbits": "trocitos de piña",
    "pinto beans": "frijoles pinto",
    "pistachio": "pistacho",
    "pistachios": "pistachos",
    "pita": "pan pita",
    "pizza": "pizza",
    "pizza crust": "masa de pizza",
    "pizza dough": "masa de pizza",
    "plain flour": "harina común",
    "plain yogurt": "yogur natural",
    "plantain": "plátano",
    "plantains": "plátanos",
    "plastic wrap": "film plástico",
    "plum": "ciruela",
    "plum tomato": "tomate ciruela",
    "plum tomatoes": "tomates ciruela",
    "plums": "ciruelas",
    "poppy seed": "semilla de amapola",
    "poppy seeds": "semillas de amapola",
    "pork": "carne de cerdo",
    "pork belly": "panceta de cerdo",
    "pork butt": "paleta de cerdo",
    "pork chop": "chuleta de cerdo",
    "pork chops": "chuletas de cerdo",
    "pork loin": "lomo de cerdo",
    "pork rib": "costilla de cerdo",
    "pork ribs": "costillas de cerdo",
    "pork roast": "asado de cerdo",
    "pork shoulder": "paleta de cerdo",
    "pork tenderloin": "lomo de cerdo tierno",
    "port": "oporto",
    "portabella mushroom": "champiñón portobello",
    "portabella mushrooms": "champiñones portobello",
    "portobello mushroom": "champiñón portobello",
    "portobello mushrooms": "champiñones portobello",
    "pot roast": "asado de res",
    "potato": "papa",
    "potato chips": "papas fritas",
    "potatoes": "papas",
    "poultry": "aves",
    "poultry seasoning": "condimento para aves",
    "powdered sugar": "azúcar impalpable",
    "provolone": "queso provolone",
    "provolone cheese": "queso provolone",
    "prune": "ciruela pasa",
    "prunes": "ciruelas pasas",
    "puff pastry": "masa hojaldre",
    "pumpkin": "zapallo",
    "pumpkin pie spice": "especia para pie de zapallo",
    "pumpkin puree": "puré de zapallo",
    "pumpkin seeds": "semillas de zapallo",
    "queso fresco": "queso fresco",
    "quinoa": "quinua",
    "radicchio": "radicchio",
    "radish": "rábano",
    "radishes": "rábanos",
    "raisins": "pasas de uva",
    "ramen": "ramen",
    "rapeseed oil": "aceite de canola",
    "raspberries": "frambuesas",
    "raspberry": "frambuesa",
    "raw shrimp": "camarón crudo",
    "red apple": "manzana roja",
    "red bell pepper": "pimiento rojo",
    "red bell peppers": "pimientos rojos",
    "red cabbage": "repollo rojo",
    "red chili": "ají rojo",
    "red chili pepper": "ají rojo picante",
    "red curry paste": "pasta de curry rojo",
    "red kidney beans": "frijoles rojos",
    "red lentil": "lenteja roja",
    "red lentils": "lentejas rojas",
    "red onion": "cebolla roja",
    "red onions": "cebollas rojas",
    "red pepper": "pimiento rojo",
    "red pepper flakes": "hojuelas de ají rojo",
    "red peppers": "pimientos rojos",
    "red potato": "papa roja",
    "red potatoes": "papas rojas",
    "red wine": "vino tinto",
    "red wine vinegar": "vinagre de vino tinto",
    "reduced-fat milk": "leche semidescremada",
    "refried beans": "frijoles refritos",
    "rhubarb": "ruibardo",
    "rib": "costilla",
    "rice": "arroz",
    "rice flour": "harina de arroz",
    "rice vinegar": "vinagre de arroz",
    "rice wine": "vino de arroz",
    "ricotta": "queso ricotta",
    "ricotta cheese": "queso ricotta",
    "roma tomato": "tomate roma",
    "roma tomatoes": "tomates roma",
    "romaine lettuce": "lechuga romana",
    "roma tomatoes": "tomates roma",
    "roma tomato": "tomate roma",
    "rosemary": "romero",
    "rosemary leaves": "hojas de romero",
    "rotini": "pasta rotini",
    "rotisserie chicken": "pollo asado",
    "round steak": "bistec de redondo",
    "rub": "sazón",
    "rum": "ron",
    "rum extract": "extracto de ron",
    "rye": "centeno",
    "rye bread": "pan de centeno",
    "rye flour": "harina de centeno",
    "saffron": "azafrán",
    "sage": "salvia",
    "sage leaves": "hojas de salvia",
    "salad dressing": "aderezo para ensalada",
    "salami": "salami",
    "salmon": "salmón",
    "salmon fillet": "filete de salmón",
    "salmon fillets": "filetes de salmón",
    "salsa": "salsa",
    "salsa verde": "salsa verde",
    "salt": "sal",
    "salted butter": "mantequilla con sal",
    "sauerkraut": "chucrut",
    "sausage": "salchicha",
    "sausages": "salchichas",
    "sausage links": "salchichas",
    "sausage meat": "carne de salchicha",
    "savory": "satureja",
    "scallion": "cebolla de verdeo",
    "scallions": "cebollas de verdeo",
    "scallop": "vieira",
    "scallops": "vieiras",
    "scotch bonnet pepper": "ají scotch bonnet",
    "sea salt": "sal marina",
    "sea scallop": "vieira de mar",
    "sea scallops": "vieiras de mar",
    "seasoned salt": "sazón",
    "seasoning": "condimento",
    "seeds": "semillas",
    "semi-sweet chocolate": "chocolate semiamargo",
    "semi-sweet chocolate chips": "chips de chocolate semiamargo",
    "serrano chili": "chile serrano",
    "serrano chilies": "chiles serranos",
    "serrano pepper": "ají serrano",
    "serrano peppers": "ajíes serranos",
    "sesame oil": "aceite de sésamo",
    "sesame seed": "semilla de sésamo",
    "sesame seeds": "semillas de sésamo",
    "shallot": "chalota",
    "shallots": "chalotas",
    "sharp cheddar cheese": "queso cheddar fuerte",
    "sheeps milk cheese": "queso de leche de oveja",
    "sherry": "jerez",
    "sherry vinegar": "vinagre de jerez",
    "shredded cheese": "queso rallado",
    "shredded coconut": "coco rallado",
    "shrimp": "camarón",
    "shrimp": "camarones",
    "shrimps": "camarones",
    "silken tofu": "tofu sedoso",
    "simple syrup": "jarabe simple",
    "skim milk": "leche descremada",
    "skinned almonds": "almendras peladas",
    "slaw mix": "mezcla para ensalada",
    "slivered almonds": "almendras fileteadas",
    "smoked paprika": "pimentón ahumado",
    "smoked salmon": "salmón ahumado",
    "smoked sausage": "salchicha ahumada",
    "smoked turkey": "pavo ahumado",
    "smooth peanut butter": "mantequilla de maní suave",
    "snapper": "pargo",
    "snow pea": "arveja china",
    "snow peas": "arvejas chinas",
    "soda": "gaseosa",
    "soda water": "agua con gas",
    "sour cream": "crema agria",
    "sourdough": "pan de masa madre",
    "soy milk": "leche de soja",
    "soy sauce": "salsa de soja",
    "soybean oil": "aceite de soja",
    "spaghetti": "espagueti",
    "spaghetti squash": "zapallo espagueti",
    "sparkling wine": "vino espumante",
    "spearmint": "menta verde",
    "spelt": "espelta",
    "spice": "especia",
    "spinach": "espinaca",
    "splenda": "splenda",
    "sprinkles": "virutas de colores",
    "sprouts": "brotes",
    "squash": "zapallo",
    "squash blossoms": "flores de zapallo",
    "squid": "calamar",
    "star anise": "anís estrellado",
    "steak": "bistec",
    "steaks": "bisteces",
    "stevia": "stevia",
    "stew": "estofado",
    "stew meat": "carne para estofado",
    "stock": "caldo",
    "strawberries": "frutillas",
    "strawberry": "frutilla",
    "stuffing": "relleno",
    "stuffing mix": "mezcla para relleno",
    "sugar": "azúcar",
    "sultanas": "pasas rubias",
    "sunflower oil": "aceite de girasol",
    "sunflower seeds": "semillas de girasol",
    "sweet and sour sauce": "salsa agridulce",
    "sweet basil": "albahaca dulce",
    "sweet cherry": "cereza dulce",
    "sweet cherries": "cerezas dulces",
    "sweet chili sauce": "salsa de ají dulce",
    "sweet corn": "choclo dulce",
    "sweet milk": "leche entera",
    "sweet onion": "cebolla dulce",
    "sweet onions": "cebollas dulces",
    "sweet paprika": "pimentón dulce",
    "sweet pepper": "pimiento dulce",
    "sweet peppers": "pimientos dulces",
    "sweet potato": "camote",
    "sweet potatoes": "camotes",
    "sweetened condensed milk": "leche condensada",
    "swiss chard": "acelga suiza",
    "swiss cheese": "queso suizo",
    "synthetic sweetener": "edulcorante artificial",
    "tabasco sauce": "salsa tabasco",
    "tahini": "tahini",
    "tamale": "tamal",
    "tamales": "tamales",
    "tamari": "salsa tamari",
    "tapioca": "tapioca",
    "tapioca flour": "harina de tapioca",
    "tapioca starch": "almidón de tapioca",
    "tarragon": "estragón",
    "tart": "tarta",
    "tartar sauce": "salsa tártara",
    "tater tots": "papitas",
    "tea": "té",
    "tequila": "tequila",
    "teriyaki sauce": "salsa teriyaki",
    "thai basil": "albahaca tailandesa",
    "thyme": "tomillo",
    "thyme leaves": "hojas de tomillo",
    "tilsit cheese": "queso tilsit",
    "tilapia": "tilapia",
    "tilapia fillet": "filete de tilapia",
    "tilapia fillets": "filetes de tilapia",
    "toast": "tostada",
    "toast bread": "pan tostado",
    "toasted almonds": "almendras tostadas",
    "toasted sesame oil": "aceite de sésamo tostado",
    "toasted sesame seeds": "semillas de sésamo tostadas",
    "tobiko": "tobiko",
    "tofu": "tofu",
    "tomato": "tomate",
    "tomato juice": "jugo de tomate",
    "tomato paste": "pasta de tomate",
    "tomato puree": "puré de tomate",
    "tomato sauce": "salsa de tomate",
    "tomatoes": "tomates",
    "top sirloin": "solomo de res",
    "tortilla": "tortilla",
    "tortilla chips": "totopos",
    "tortillas": "tortillas",
    "triple sec": "triple sec",
    "trout": "trucha",
    "trout fillet": "filete de trucha",
    "trout fillets": "filetes de trucha",
    "tuna": "atún",
    "tuna fillet": "filete de atún",
    "tuna fillets": "filetes de atún",
    "tuna steak": "bistec de atún",
    "tuna steaks": "bistes de atún",
    "turkey": "pavo",
    "turkey breast": "pechuga de pavo",
    "turkey breasts": "pechugas de pavo",
    "turkey stock": "caldo de pavo",
    "turmeric": "cúrcuma",
    "turnip": "nabo",
    "turnips": "nabos",
    "turnip greens": "nabizas",
    "turtle": "tortuga",
    "udon": "fideos udon",
    "unbleached flour": "harina sin blanquear",
    "unsalted butter": "mantequilla sin sal",
    "vanilla": "vainilla",
    "vanilla extract": "extracto de vainilla",
    "vanilla ice cream": "helado de vainilla",
    "vanilla pudding": "pudín de vainilla",
    "vanilla wafer": "galleta de vainilla",
    "vanilla wafers": "galletas de vainilla",
    "vanilla yogurt": "yogur de vainilla",
    "veal": "ternera",
    "veal chop": "chuleta de ternera",
    "veal chops": "chuletas de ternera",
    "vegetable": "verdura",
    "vegetable broth": "caldo de verduras",
    "vegetable oil": "aceite vegetal",
    "vegetable shortening": "acortamiento vegetal",
    "vegetable soup": "sopa de verduras",
    "vegetable stock": "caldo de verduras",
    "vegetables": "verduras",
    "vegetarian": "vegetariano",
    "velveeta": "queso velveeta",
    "vermouth": "vermú",
    "vidalia onion": "cebolla vidalia",
    "vital wheat gluten": "gluten de trigo vital",
    "vodka": "vodka",
    "waffle": "gofre",
    "waffles": "gofres",
    "walnut": "nuez",
    "walnuts": "nueces",
    "wasabi": "wasabi",
    "water": "agua",
    "water chestnut": "castaña de agua",
    "water chestnuts": "castañas de agua",
    "watercress": "berro",
    "watermelon": "sandía",
    "watermelon chunks": "trozos de sandía",
    "wheat": "trigo",
    "wheat bran": "salvado de trigo",
    "wheat flour": "harina de trigo",
    "wheat gluten": "gluten de trigo",
    "wheat germ": "germen de trigo",
    "whipped cream": "crema chantillí",
    "whipped topping": "cobertura batida",
    "whiskey": "whisky",
    "white beans": "frijoles blancos",
    "white bread": "pan blanco",
    "white cake mix": "mezcla para pastel blanco",
    "white chocolate": "chocolate blanco",
    "white pepper": "pimienta blanca",
    "white pepper powder": "pimienta blanca en polvo",
    "white sugar": "azúcar blanca",
    "white vinegar": "vinagre blanco",
    "white wine": "vino blanco",
    "white wine vinegar": "vinagre de vino blanco",
    "whole allspice": "pimienta de jamaica en grano",
    "whole almonds": "almendras enteras",
    "whole chicken": "pollo entero",
    "whole cloves": "clavos de olor enteros",
    "whole coriander seeds": "semillas de cilantro enteras",
    "whole cranberry sauce": "salsa de arándano rojo",
    "whole cumin seeds": "semillas de comino enteras",
    "whole kernel corn": "choclo entero",
    "whole kernel corn, drained": "choclo entero escurrido",
    "whole milk": "leche entera",
    "whole mustard seed": "semilla de mostaza entera",
    "whole mustard seeds": "semillas de mostaza enteras",
    "whole nutmeg": "nuez moscada entera",
    "whole nutmegs": "nueces moscadas enteras",
    "whole pearl onions": "cebollitas perla enteras",
    "whole wheat": "trigo integral",
    "whole wheat flour": "harina de trigo integral",
    "wine": "vino",
    "wine vinegar": "vinagre de vino",
    "winter savory": "satureja de invierno",
    "wonton": "wonton",
    "wonton wrappers": "hojas de wonton",
    "worcestershire sauce": "salsa worcestershire",
    "wraps": "wraps",
    "wheat": "trigo",
    "xanthan gum": "goma xantana",
    "yeast": "levadura",
    "yellow cake mix": "mezcla para pastel amarillo",
    "yellow corn": "choclo amarillo",
    "yellow onion": "cebolla amarilla",
    "yellow onions": "cebollas amarillas",
    "yellow squash": "zapallo amarillo",
    "yogurt": "yogur",
    "yogurt cheese": "queso de yogur",
    "zucchini": "zapallito italiano",
    "zucchinis": "zapallitos italianos",
    "dry penne pasta": "pasta penne seca",
    "penne pasta": "pasta penne",
    "penne": "pasta penne",
    "farfalle pasta": "pasta farfalle",
    "farfalle": "pasta farfalle",
    "fettuccine pasta": "pasta fettuccine",
    "fettuccine": "pasta fettuccine",
    "flour": "harina",
    "fresh corn": "choclo fresco",
    "fresh corn kernels": "granos de choclo fresco",
    "frozen corn": "choclo congelado",
    "besan flour": "harina de garbanzo",
}


_CATEGORY_KEYWORDS = {
    'Aceites y Vinagres': [
        'aceite', 'aceite de oliva', 'aceite vegetal', 'aceite de girasol',
        'vinagre', 'vinagreta', 'vinagre de',
        'oil', 'olive oil', 'vegetable oil', 'sunflower oil',
        'cooking oil', 'vinegar', 'cooking spray',
        'aioli', 'aioli sauce',
    ],
    'Condimentos y Endulzantes': [
        'sal', 'sal marina', 'sal gorda',
        'azúcar', 'azúcar rubia', 'azúcar moreno', 'azúcar blanca',
        'miel', 'miel de abeja', 'miel maple', 'maple syrup',
        'melaza', 'panela', 'chancaca',
        'mostaza', 'kétchup', 'ketchup', 'mayonesa', 'mayo',
        'salsa de soja', 'soy sauce', 'salsa inglesa', 'worcestershire',
        'hot sauce', 'sriracha', 'salsa',
        'sugar', 'salt', 'honey', 'syrup', 'molasses',
        'mustard', 'ketchup', 'mayonnaise',
        'accent seasoning', 'adobo', 'adobo seasoning', 'adobo sauce',
    ],
    'Hierbas y Especias': [
        'ajo', 'almendra', 'culantro', 'cilantro', 'perejil', 'menta',
        'hierbabuena', 'albahaca', 'orégano', 'comino',
        'pimienta', 'canela', 'clavo', 'nuez moscada', 'jengibre',
        'ginger', 'curry', 'achiote', 'sazón', 'sazon',
        'cúrcuma', 'turmeric', 'paprika', 'pimentón',
        'anís', 'anis', 'hinojo', 'fennel', 'laurel', 'bay leaf',
        'romero', 'rosemary', 'tomillo', 'thyme', 'mejorana', 'marjoram',
        'garlic', 'basil',
        'allspice', 'black pepper', 'white pepper', 'peppercorn',
        'pepper', 'chili', 'chile', 'ají', 'aji',
        'advieh', 'ajwain', 'ajwain seed',
        'aleppo pepper', 'annatto', 'annatto seed', 'annatto seeds',
        'coriander', 'cumin', 'paprika', 'saffron',
        'lemongrass', 'lemons',
    ],
    'Huevos': [
        'huevo', 'huevos', 'clara', 'yema',
        'egg', 'eggs', 'egg white', 'egg yolk',
    ],
    'Panificados': [
        'pan', 'pan lactal', 'pan francés', 'pan integral',
        'tortilla', 'tortillas', 'masa', 'masa de taco', 'masa de tamal',
        'hoja de tamal', 'hoja de plátano',
        'arepa', 'bollo', 'cachanga', 'empanada',
        'bread', 'toast', 'toast bread', 'roll', 'bun', 'buns',
        'croissant', 'baguette', 'pita', 'pizza dough',
        'french fries', 'fries',
    ],
    'Tubérculos': [
        'papa', 'camote', 'yuca', 'oca', 'olluco', 'mashua', 'arracacha',
        'potato', 'sweet potato', 'cassava', 'yam', 'taro',
        'nabo', 'rábano', 'remolacha', 'rabanito', 'berro',
    ],
    'Verduras': [
        'cebolla', 'cebollín', 'cebolla de verdeo', 'tomate', 'loche',
        'lechuga', 'repollo', 'col', 'zapallo', 'calabaza', 'pepino',
        'pimiento', 'pimentón', 'morron', 'choclo', 'maíz',
        'berenjena', 'vainita', 'ejote', 'brócoli', 'coliflor',
        'rúcula', 'alcachofa', 'espinaca', 'acelga',
        'apio', 'chícharo', 'guisante', 'arveja', 'haba verde', 'brote de',
        'squash', 'onion', 'tomato', 'lettuce', 'cabbage', 'cucumber',
        'eggplant', 'aubergine', 'broccoli', 'cauliflower', 'spinach',
        'celery', 'peppers', 'pimento pepper', 'bell pepper', 'sweet pepper',
        'chili pepper', 'chile pepper',
    ],
    'Granos y Cereales': [
        'arroz', 'quinua', 'kiwicha', 'canihua', 'amaranto',
        'cebada', 'avena', 'maíz', 'choclo', 'trigo',
        'harina de trigo', 'harina', 'sémola', 'maicena',
        'fideo', 'pasta', 'espagueti', 'macarrones', 'fideos',
        'canelones', 'lasaña', 'ravioles', 'tallarines',
        'rice', 'quinoa', 'barley', 'oats', 'oat',
        'corn', 'flour', 'pasta', 'spaghetti', 'noodle', 'noodles',
        'couscous', 'bulgur', 'millet', 'tortilla chips',
        'amaranth', 'breadcrumbs', 'bread crumb', 'bread crumbs',
        'panko', 'breadcrumb',
    ],
    'Legumbres': [
        'frejol', 'frijol', 'frijoles', 'frejoles',
        'lenteja', 'lentejas',
        'garbanzo', 'garbanzos',
        'haba', 'habas',
        'arveja', 'arvejas', 'guisante', 'guisantes',
        'fríjol', 'frijoles negros', 'frijoles rojos',
        'pallar', 'pallares', 'lupini',
        'beans', 'lentils', 'chickpea', 'chickpeas', 'pea', 'peas',
        'black bean', 'red bean', 'kidney bean', 'navy bean',
        'soybean', 'soja',
        'alfalfa', 'sprout', 'sprouts',
    ],
    'Lácteos': [
        'leche', 'leche evaporada', 'leche condensada', 'leche en polvo',
        'queso', 'quesillo', 'queso fresco', 'queso parmesano', 'parmesano',
        'queso azul', 'roquefort', 'cheddar', 'mozzarella', 'gouda',
        'manchego', 'crema', 'crema de leche', 'crema agria', 'crema espesa',
        'nata', 'mantequilla', 'manteca', 'manteca de cerdo',
        'yogur', 'yogurt', 'lechera', 'evaporada', 'condensada',
        'milk', 'cheese', 'cream', 'butter', 'yogurt', 'yoghurt',
        'buttermilk', 'sour cream',
        'alfredo sauce', 'almesan',
        'parmesan', 'provolone', 'ricotta', 'feta',
        'ghee', 'clarified butter',
    ],
    'Proteínas': [
        'pollo', 'pavo', 'patito', 'pato', 'res', 'carne', 'carne molida',
        'cerdo', 'chancho', 'puerco', 'jamón', 'tocino', 'bacon',
        'chorizo', 'morcilla', 'salchicha', 'hot dog', 'hamburguesa',
        'pescado', 'corvina', 'jurel', 'cabrilla', 'tollo', 'perico',
        'anchoveta', 'sardina', 'sardine', 'atún', 'bonito',
        'salmón', 'salmon', 'trucha', 'trout', 'camarón', 'camarones',
        'pota', 'calamar', 'pulpo', 'cefalópodo', 'mariscos',
        'beef', 'chicken', 'pork', 'turkey', 'duck', 'fish', 'meat',
        'steak', 'roast', 'shoulder', 'breast', 'thigh', 'wing',
        'filete', 'filetes',
        'shrimp', 'prawn', 'crab', 'lobster', 'clam', 'mussel',
        'oyster', 'scallop', 'anchov', 'sard',
        'ahi', 'ahi tuna', 'ahi tuna steaks',
        'anchovy', 'anchovies', 'tilapia',
        'sausage', 'sausages', 'andouille',
        'seafood', 'crabmeat', 'crawfish', 'lobster meat',
    ],
    'Frutas': [
        'limón', 'lima', 'naranja', 'plátano', 'banano', 'mango',
        'papaya', 'piña', 'anana', 'manzana', 'pera', 'uva',
        'sandía', 'melón', 'frutilla', 'fresa', 'chirimoya',
        'guanábana', 'lúcuma', 'aguaymanto', 'tumbo', 'granadilla',
        'maracuyá', 'coco', 'palta', 'aguacate', 'lemon', 'lime',
        'orange', 'banana', 'apple', 'pineapple', 'pear', 'grape',
        'berry', 'berries', 'strawberry', 'raspberry', 'blueberry',
        'coconut', 'avocado', 'tamarind',
    ],
}


_CATEGORY_PATTERNS = {}
for _cat_name, _keywords in _CATEGORY_KEYWORDS.items():
    _pattern = r'(?:^|\s|\W)(' + '|'.join(re.escape(k) for k in _keywords) + r')(?:\s|\W|$)'
    _CATEGORY_PATTERNS[_cat_name] = re.compile(_pattern, re.IGNORECASE)


def _categorize(ingredient: str) -> str:
    text = ' ' + _strip_accents(ingredient).lower() + ' '
    for cat, pattern in _CATEGORY_PATTERNS.items():
        if pattern.search(text):
            return cat
    return "Otros"


@lru_cache(maxsize=50000)
def _clean_cached(raw: str) -> str:
    return _clean_ingredient_name(raw)


@lru_cache(maxsize=50000)
def _categorize_cached(ingredient: str) -> str:
    return _categorize(ingredient)


def _get_category_key(category: str) -> int:
    order = [
        'Tubérculos', 'Verduras', 'Hierbas y Especias', 'Frutas',
        'Proteínas', 'Lácteos', 'Granos y Cereales', 'Legumbres',
        'Huevos', 'Aceites y Vinagres', 'Panificados',
        'Condimentos y Endulzantes', 'Otros'
    ]
    try:
        return order.index(category)
    except ValueError:
        return len(order)


class RecipeService:
    def __init__(self, db_session):
        self.db = db_session

    def match_recipes_by_ingredients(self, ingredients: List[str], limit: int = 10) -> List[Dict[str, Any]]:
        if not ingredients:
            return []

        user_set = set(_normalize(i) for i in ingredients if i.strip())
        if not user_set:
            return []

        recipes = self.db.query(Recipe).all()
        scored: List[Dict[str, Any]] = []

        for recipe in recipes:
            recipe_ings = json.loads(recipe.ingredients)
            recipe_set = set(_normalize(i) for i in recipe_ings)

            matched_user_ings = set()
            matched_recipe_ings = set()
            for user_ing in user_set:
                for rec_ing in recipe_set:
                    if _ingredients_match(user_ing, rec_ing):
                        matched_user_ings.add(user_ing)
                        matched_recipe_ings.add(rec_ing)
                        break

            matched_count = len(matched_user_ings)
            missing_count = len(recipe_set) - len(matched_recipe_ings)
            recipe_total = len(recipe_set)
            user_total = len(user_set)

            if recipe_total == 0 or user_total == 0:
                continue

            coverage = matched_count / recipe_total
            match_ratio = matched_count / user_total
            missing_ratio = missing_count / recipe_total

            min_matches = max(2, user_total // 2)
            if matched_count < min_matches:
                continue

            final_score = coverage * 100 * match_ratio

            matched_list = sorted(matched_user_ings)
            missing_list = sorted(recipe_set - matched_recipe_ings)
            recipe_ings_normalized = sorted(recipe_set)

            scored.append({
                "id": recipe.id,
                "name": recipe.name,
                "description": recipe.description,
                "ingredients": recipe_ings,
                "prep_time_minutes": recipe.prep_time_minutes,
                "difficulty": recipe.difficulty,
                "region": recipe.region,
                "match_score": round(final_score, 1),
                "coverage": round(coverage * 100, 1),
                "matched_count": matched_count,
                "missing_count": missing_count,
                "matched_ingredients": matched_list,
                "missing_ingredients": missing_list,
                "image_url": recipe.image_url,
                "tags": json.loads(recipe.tags) if recipe.tags else [],
                "nutritional_info": json.loads(recipe.nutritional_info) if recipe.nutritional_info else {},
                "servings": recipe.servings,
                "source_dataset": recipe.source_dataset,
            })

        scored.sort(key=lambda x: (x["match_score"], x["coverage"]), reverse=True)
        return scored[:limit]

    def get_recipe_by_id(self, recipe_id: int) -> Dict[str, Any] | None:
        recipe = self.db.query(Recipe).filter(Recipe.id == recipe_id).first()
        if not recipe:
            return None

        return {
            "id": recipe.id,
            "name": recipe.name,
            "description": recipe.description,
            "ingredients": json.loads(recipe.ingredients),
            "steps": json.loads(recipe.steps) if recipe.steps else [],
            "prep_time_minutes": recipe.prep_time_minutes,
            "difficulty": recipe.difficulty,
            "region": recipe.region,
            "image_url": recipe.image_url,
            "tags": json.loads(recipe.tags) if recipe.tags else [],
            "nutritional_info": json.loads(recipe.nutritional_info) if recipe.nutritional_info else {},
            "servings": recipe.servings,
            "source_dataset": recipe.source_dataset,
            "enrichment": _generate_enrichment(recipe),
        }

    def search_recipes(self, query: str, limit: int = 20) -> List[Dict[str, Any]]:
        query_lower = query.lower()
        recipes = self.db.query(Recipe).all()
        results = []

        for recipe in recipes:
            if (query_lower in recipe.name.lower() or
                query_lower in (recipe.description or "").lower() or
                (recipe.tags and query_lower in recipe.tags.lower())):
                results.append({
                    "id": recipe.id,
                    "name": recipe.name,
                    "description": recipe.description,
                    "ingredients": json.loads(recipe.ingredients),
                    "prep_time_minutes": recipe.prep_time_minutes,
                    "difficulty": recipe.difficulty,
                    "region": recipe.region,
                    "image_url": recipe.image_url,
                    "tags": json.loads(recipe.tags) if recipe.tags else [],
                    "nutritional_info": json.loads(recipe.nutritional_info) if recipe.nutritional_info else {},
                    "servings": recipe.servings,
                    "source_dataset": recipe.source_dataset,
                })

        return results[:limit]

    def search_recipe_names(self, query: str, limit: int = 20) -> List[Dict[str, Any]]:
        q = _normalize(query)
        if not q:
            return []
        recipes = self.db.query(Recipe).all()
        matches = []
        for recipe in recipes:
            name_norm = _normalize(recipe.name or "")
            if q in name_norm:
                matches.append((not name_norm.startswith(q), len(recipe.name or ""), recipe.id, recipe.name))
        matches.sort(key=lambda x: (x[0], x[1], x[3]))
        return [{"id": m[2], "name": m[3]} for m in matches[:limit]]

    def get_all_unique_ingredients(self) -> List[str]:
        recipes = self.db.query(Recipe).all()
        all_ings = set()
        for recipe in recipes:
            ings = json.loads(recipe.ingredients)
            for ing in ings:
                cleaned = _clean_ingredient_name(ing)
                if cleaned:
                    all_ings.add(cleaned.lower())
        return sorted(all_ings)

    def get_ingredients_categorized(self) -> Dict[str, List[str]]:
        recipes = self.db.query(Recipe).all()
        categorized: Dict[str, set] = {}
        for recipe in recipes:
            ings = json.loads(recipe.ingredients)
            for ing in ings:
                cleaned = _clean_cached(ing)
                if not cleaned:
                    continue
                cat = _categorize_cached(cleaned)
                categorized.setdefault(cat, set()).add(cleaned.lower())
        order = [
            'Aceites y Vinagres', 'Condimentos y Endulzantes', 'Hierbas y Especias',
            'Huevos', 'Panificados', 'Tubérculos', 'Verduras',
            'Granos y Cereales', 'Legumbres', 'Lácteos', 'Proteínas',
            'Frutas', 'Otros'
        ]
        result = {}
        for cat in order:
            if cat in categorized:
                result[cat] = sorted(categorized[cat])
        for cat, ings in categorized.items():
            if cat not in result:
                result[cat] = sorted(ings)
        return result


def _generate_enrichment(recipe) -> Dict[str, Any]:
    """Genera notas estilo recetario a partir de los datos de la receta.

    Consejos prácticos derivados de ingredientes, región y tipo de cocción.
    """
    tips: List[str] = []
    try:
        ingredients = json.loads(recipe.ingredients or "[]")
    except Exception:
        ingredients = []
    text = " ".join(ingredients).lower()
    region = (recipe.region or "").lower()
    category = (recipe.tags[0] if isinstance(recipe.tags, list) and recipe.tags else "").lower() if recipe.tags else ""

    tips.append("Emplea ingredientes frescos y de temporada para realzar el sabor del plato.")

    if "costa" in region:
        tips.append("Plato de la costa peruana: acompáñalo con papa sancochada, camote o arroz.")
    elif "sierra" in region:
        tips.append("Típico de la sierra: queda excelente con papas, maíz o queso.")
    elif "selva" in region:
        tips.append("De la selva peruana: combina bien con plátano, yuca o chonta.")

    if any(k in text for k in ["limon", "cebolla", "marinar", "vinagre", "vinagreta"]):
        tips.append("Marina con anticipación para que los sabores se integren mejor.")
    if any(k in text for k in ["horno", "asado", "hornear", "asar", "parrilla"]):
        tips.append("Precalienta el horno o la parrilla y controla la temperatura durante la cocción.")
    if any(k in text for k in ["ají", "aji", "picante", "chile", "chili"]):
        tips.append("Ajusta la cantidad de ají al nivel de picante que prefieras.")
    if any(k in text for k in ["caldo", "hervir", "herv", "sancoch"]):
        tips.append("Deja el caldo a fuego lento para concentrar el sabor.")
    if any(k in text for k in ["freir", "frito", "aceite"]):
        tips.append("Drena sobre papel absorbente para retirar el exceso de grasa.")
    if "postre" in category or "dulce" in category:
        tips.append("En repostería, respeta las medidas y no te saltes los tiempos de reposo.")

    seen = set()
    out = []
    for t in tips:
        if t not in seen:
            seen.add(t)
            out.append(t)
    return {"tips": out[:4]}


def _ingredients_match(user_ing: str, recipe_ing: str) -> bool:
    """Determina si un ingrediente del usuario coincide con uno de la receta."""
    if user_ing == recipe_ing:
        return True
    if user_ing in recipe_ing or recipe_ing in user_ing:
        return True
    return False
